#!/bin/bash

# Cyber Citadel CTF Platform - Main Platform Deployment Script
# Run this script on your Main Platform DigitalOcean Droplet

set -e  # Exit on error

echo "=================================="
echo "CTF Platform - Main Platform Setup"
echo "=================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored messages
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "Please run as root (use sudo)"
    exit 1
fi

# Update system
print_info "Updating system packages..."
apt update && apt upgrade -y

# Install necessary packages
print_info "Installing necessary packages..."
apt install -y curl wget git nginx certbot python3-certbot-nginx ufw software-properties-common

# Install Node.js
print_info "Installing Node.js 18.x..."
if ! command -v node &> /dev/null; then
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    apt install -y nodejs
fi

NODE_VERSION=$(node --version)
NPM_VERSION=$(npm --version)
print_info "Node.js version: $NODE_VERSION"
print_info "npm version: $NPM_VERSION"

# Install PM2
print_info "Installing PM2..."
npm install -g pm2

# Install Docker (for vulnerable containers)
print_info "Installing Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    usermod -aG docker $USER
    systemctl start docker
    systemctl enable docker
fi

# Install Docker Compose
print_info "Installing Docker Compose..."
if ! command -v docker-compose &> /dev/null; then
    curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
fi

# Setup project directory
PROJECT_DIR="/var/www/ctf-platform"
print_info "Setting up project directory: $PROJECT_DIR"
mkdir -p $PROJECT_DIR

# Check if repository exists
if [ -d "$PROJECT_DIR/.git" ]; then
    print_info "Repository found. Updating..."
    cd $PROJECT_DIR
    git pull
else
    print_warn "Repository not found. Please upload your code to $PROJECT_DIR"
    print_info "You can use: git clone <your-repo> $PROJECT_DIR"
fi

# Setup backend
if [ -d "$PROJECT_DIR/backend" ]; then
    print_info "Setting up backend..."
    cd $PROJECT_DIR/backend
    npm install --production

    # Create .env file
    if [ ! -f ".env" ]; then
        print_info "Creating .env file..."
        cat > .env << 'EOF'
NODE_ENV=production
PORT=5001
MONGODB_URI=mongodb://YOUR_DB_DROPLET_IP:27017/ctf-platform
JWT_SECRET=change_this_to_a_secure_random_string_in_production
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin123
UNIVERSITY_CODE=SUPER
EOF
        print_warn "Please edit $PROJECT_DIR/backend/.env with your actual database IP and secure secrets!"
    fi
else
    print_error "Backend directory not found at $PROJECT_DIR/backend"
fi

# Setup frontend
if [ -d "$PROJECT_DIR/frontend" ]; then
    print_info "Setting up frontend..."
    cd $PROJECT_DIR/frontend
    npm install

    # Create production .env
    print_info "Creating production .env..."
    read -p "Enter your domain (e.g., ctf.yourdomain.com): " DOMAIN
    cat > .env.production << EOF
VITE_API_URL=https://$DOMAIN/api
EOF

    # Build frontend
    print_info "Building frontend for production..."
    npm run build
else
    print_error "Frontend directory not found at $PROJECT_DIR/frontend"
fi

# Setup PM2
if [ -f "$PROJECT_DIR/backend/ecosystem.config.js" ]; then
    print_info "Starting backend with PM2..."
    cd $PROJECT_DIR/backend
    pm2 start ecosystem.config.js
    pm2 save
    pm2 startup
else
    print_warn "PM2 ecosystem config not found. Creating..."
    cat > $PROJECT_DIR/backend/ecosystem.config.js << 'EOF'
module.exports = {
  apps: [{
    name: 'ctf-platform-backend',
    script: './src/index.js',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      PORT: 5001
    }
  }]
};
EOF
    pm2 start $PROJECT_DIR/backend/ecosystem.config.js
fi

# Setup Nginx
print_info "Setting up Nginx..."
read -p "Enter your domain (e.g., ctf.yourdomain.com): " DOMAIN

cat > /etc/nginx/sites-available/ctf-platform << EOF
server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN;

    # Redirect HTTP to HTTPS
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN www.$DOMAIN;

    # SSL Configuration (will be auto-generated by certbot)
    # ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    # Frontend (React build)
    location / {
        root $PROJECT_DIR/frontend/dist;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }

    # API Backend
    location /api/ {
        proxy_pass http://localhost:5001/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOF

# Enable site
ln -sf /etc/nginx/sites-available/ctf-platform /etc/nginx/sites-enabled/

# Test nginx
if nginx -t; then
    print_info "Nginx configuration is valid"
    systemctl restart nginx
    systemctl enable nginx
else
    print_error "Nginx configuration test failed!"
fi

# Setup Firewall
print_info "Configuring firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 5001/tcp
ufw --force enable

# Install Fail2Ban
print_info "Installing and configuring Fail2Ban..."
apt install -y fail2ban
cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3

[sshd]
enabled = true

[nginx-http-auth]
enabled = true
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 3
EOF
systemctl enable fail2ban
systemctl start fail2ban

# Setup log rotation
print_info "Setting up log rotation..."
cat > /etc/logrotate.d/ctf-platform << EOF
$PROJECT_DIR/backend/logs/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    copytruncate
}
EOF

# Create backup script
print_info "Creating backup script..."
cat > /root/backup-ctf-platform.sh << 'EOF'
#!/bin/bash
BACKUP_DIR="/root/ctf-backups"
DATE=$(date +%Y%m%d_%H%M%S)
PROJECT_DIR="/var/www/ctf-platform"

mkdir -p $BACKUP_DIR

# Backup backend
cd $PROJECT_DIR/backend
tar -czf $BACKUP_DIR/backend_$DATE.tar.gz .env ecosystem.config.js

# Backup frontend
cd $PROJECT_DIR/frontend
tar -czf $BACKUP_DIR/frontend_$DATE.tar.gz .env.production

# Keep only last 7 days of backups
find $BACKUP_DIR -type f -mtime +7 -delete

echo "Backup completed: $DATE"
EOF

chmod +x /root/backup-ctf-platform.sh

# Add to crontab
(crontab -l 2>/dev/null; echo "0 2 * * * /root/backup-ctf-platform.sh") | crontab -

print_info "=================================="
print_info "Setup Complete!"
print_info "=================================="
print_info ""
print_info "Next steps:"
print_info "1. Update $PROJECT_DIR/backend/.env with your database IP"
print_info "2. Setup your database droplet (see DEPLOYMENT_GUIDE.md)"
print_info "3. Run: certbot --nginx -d $DOMAIN -d www.$DOMAIN"
print_info "4. Restart services: pm2 restart all && systemctl restart nginx"
print_info ""
print_info "Useful commands:"
print_info "  - View backend logs: pm2 logs"
print_info "  - View nginx logs: tail -f /var/log/nginx/error.log"
print_info "  - Run backup: /root/backup-ctf-platform.sh"
print_info ""
